name: Add Video via Dispatch

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  add-video:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine trigger context
        id: guard
        run: python determine_trigger.py

      - name: Parse issue command
        if: steps.guard.outputs.issue_mode == 'true'
        id: parse
        env:
          PAYLOAD: ${{ steps.guard.outputs.raw_command }}
        run: |
          python parse_issue_command.py

      - name: Append video entry
        if: steps.guard.outputs.should_run == 'true'
        env:
          LINK: ${{ steps.parse.outputs.LINK }}
          TITLE: ${{ steps.parse.outputs.TITLE }}
          CHANNEL: ${{ steps.parse.outputs.CHANNEL }}
        run: |
          python append_video_entry.py \
            --link "$LINK" \
            --title "$TITLE" \
            --channel "$CHANNEL"

      - name: Generate README
        if: steps.guard.outputs.should_run == 'true'
        run: make readme

      - name: Create Pull Request
        if: steps.guard.outputs.should_run == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add video: ${{ steps.parse.outputs.TITLE }}"
          branch: "bot/add-video-${{ github.run_id }}"
          title: "Add video: ${{ steps.parse.outputs.TITLE }}"
          body: |
            Добавлено новое видео:
            - Канал: `${{ steps.parse.outputs.CHANNEL }}`
            - Название: `${{ steps.parse.outputs.TITLE }}`
            - Ссылка: `${{ steps.parse.outputs.LINK }}`
          add-paths: |
            list.json
            README.md
