name: Add Video via Dispatch

on:
  workflow_dispatch:
    inputs:
      link:
        description: "YouTube ссылка (https://www.youtube.com/... или https://youtu.be/...)"
        required: true
      title:
        description: "Название видео"
        required: true
      channel:
        description: "Название канала"
        required: true

jobs:
  add-video:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Append video entry
        env:
          LINK: ${{ inputs.link }}
          TITLE: ${{ inputs.title }}
          CHANNEL: ${{ inputs.channel }}
        run: |
          python append_video_entry.py \
            --link "$LINK" \
            --title "$TITLE" \
            --channel "$CHANNEL"

      - name: Generate README
        run: make readme

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add video: ${{ inputs.title }}"
          branch: "bot/add-video-${{ github.run_id }}"
          title: "Add video: ${{ inputs.title }}"
          body: |
            Добавлено новое видео:
            - Канал: `${{ inputs.channel }}`
            - Название: `${{ inputs.title }}`
            - Ссылка: `${{ inputs.link }}`
          add-paths: |
            list.json
            README.md
